---
version: 4
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: tpdb_user
          PGDB: tpdb_ci
          PGPW: "tpdb1234!"
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: tpdb_user
          POSTGRES_DB: tpdb_ci
          POSTGRES_PASSWORD: "tpdb1234!"
    steps:
      - checkout

      # Restore Cached Dependencies
      - restore_cache:
          name: Restore bundle cache
          key: tpdb-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run:
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment

      # Cache Dependencies
      - save_cache:
          name: Store bundle cache
          key: tpdb-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Wait for DB
      - run: 
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the database
      - run: 
          name: Setup DB
          command: bundle exec rake db:setup

      # Run the tests
      - run: 
          name: Make rspec directory
          command: mkdir ~/rspec
      - run: 
          name: Run tests
          command: bundle exec rspec --format progress 
                                     --format RspecJunitFormatter 
                                     -o ~/rspec/rspec.xml

      - store_test_results:
          path: ~/rspec
        
