name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:9.5
        ports: ['5432:5432']
        env:
          POSTGRES_USER: tpdb_user
          POSTGRES_DB: tpdb_ci
          POSTGRES_PASSWORD: tpdb1234
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.3
    - name: Build and test with Rake
      env:
        PGHOST: localhost
        PGUSER: tpdb_user
        PGDB: tpdb_ci
        PGPW: tpdb1234
        RAILS_ENV: test
        RACK_ENV: test
      run: |
        gem install bundler:1.17.3
        bundle install --jobs 4 --retry 3
        bundle exec rake db:setup
        bundle exec rspec
