name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:9.5
        ports: ['5432:5432']
        env:
          POSTGRES_USER: tpdb_user
          POSTGRES_DB: tpdb_ci
          POSTGRES_PASSWORD: tpdb1234
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        
    env:
      PGHOST: localhost
      PGUSER: tpdb_user
      PGDB: tpdb_ci
      PGPW: tpdb1234
      RAILS_ENV: test
      RACK_ENV: test

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5.3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5.3
    - name: Install Bundler
      run: |
        gem install bundler:1.17.3
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby }}-
    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --deployment
    - name: Set up DB
      run: bundle exec rake db:setup
    - name: Run rspec tests
      run: |
        mkdir rspec
        bundle exec rspec --format progress --format RspecJunitFormatter -o rspec/rspec.xml
    - name: Junit Report to Annotations
      uses: ashley-taylor/junit-report-annotations-action@v1.0
      with:
        # github token
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: rspec/*.xml
        includeSummary: true
        testSrcPath: test/
